// Mock data for Idealize 360º Platform

export const units = [
  { id: "1", name: "Matriz - São Paulo", city: "São Paulo", state: "SP", manager: "Carlos Silva" },
  { id: "2", name: "Unidade Campinas", city: "Campinas", state: "SP", manager: "Ana Souza" },
  { id: "3", name: "Unidade Ribeirão Preto", city: "Ribeirão Preto", state: "SP", manager: "Pedro Santos" },
  { id: "4", name: "Unidade Curitiba", city: "Curitiba", state: "PR", manager: "Maria Oliveira" },
  { id: "5", name: "Unidade Belo Horizonte", city: "Belo Horizonte", state: "MG", manager: "João Pereira" },
];

export const roles = [
  { id: "1", name: "Consultor de Vendas", department: "Comercial" },
  { id: "2", name: "Pós-venda", department: "Atendimento" },
  { id: "3", name: "Técnico de Laboratório", department: "Operações" },
  { id: "4", name: "Gestor de Unidade", department: "Gestão" },
  { id: "5", name: "Analista de RH", department: "Recursos Humanos" },
  { id: "6", name: "Coordenador Comercial", department: "Comercial" },
];

export const jobs = [
  {
    id: "1",
    title: "Consultor de Vendas",
    unit: units[0],
    description: "Buscamos um consultor de vendas para atender clientes na loja matriz. O profissional será responsável por todo o processo de vendas, desde a recepção até o fechamento.",
    requirements: ["Experiência em vendas", "Boa comunicação", "Ensino médio completo"],
    benefits: ["Vale transporte", "Vale refeição", "Comissão", "Plano de saúde"],
    salary: "R$ 2.500 - R$ 4.500",
    type: "CLT",
    status: "open",
    createdAt: "2024-01-15",
    applications: 24,
  },
  {
    id: "2",
    title: "Técnico de Laboratório",
    unit: units[1],
    description: "Vaga para técnico de laboratório óptico. O profissional será responsável pela confecção e ajuste de lentes.",
    requirements: ["Curso técnico em óptica", "Experiência com surfaçagem", "Atenção aos detalhes"],
    benefits: ["Vale transporte", "Vale refeição", "Plano de saúde", "PLR"],
    salary: "R$ 3.000 - R$ 4.000",
    type: "CLT",
    status: "open",
    createdAt: "2024-01-20",
    applications: 12,
  },
  {
    id: "3",
    title: "Pós-venda",
    unit: units[2],
    description: "Responsável pelo atendimento pós-venda, garantindo a satisfação dos clientes e resolução de problemas.",
    requirements: ["Experiência em atendimento", "Paciência", "Proatividade"],
    benefits: ["Vale transporte", "Vale refeição", "Plano de saúde"],
    salary: "R$ 2.200 - R$ 2.800",
    type: "CLT",
    status: "open",
    createdAt: "2024-01-22",
    applications: 18,
  },
];

export const candidates = [
  {
    id: "1",
    name: "Mariana Costa",
    email: "mariana.costa@email.com",
    phone: "(11) 98765-4321",
    jobId: "1",
    unitId: "1",
    status: "interview",
    appliedAt: "2024-01-18",
    discProfile: "I",
    temperament: "Sanguíneo",
    resumeUrl: "/resumes/mariana-costa.pdf",
    notes: "Excelente comunicação. Experiência prévia em ótica.",
  },
  {
    id: "2",
    name: "Rafael Mendes",
    email: "rafael.mendes@email.com",
    phone: "(11) 91234-5678",
    jobId: "1",
    unitId: "1",
    status: "new",
    appliedAt: "2024-01-20",
    discProfile: "D",
    temperament: "Colérico",
    resumeUrl: "/resumes/rafael-mendes.pdf",
    notes: "",
  },
  {
    id: "3",
    name: "Juliana Ferreira",
    email: "juliana.ferreira@email.com",
    phone: "(19) 98888-7777",
    jobId: "2",
    unitId: "2",
    status: "evaluating",
    appliedAt: "2024-01-21",
    discProfile: "C",
    temperament: "Melancólico",
    resumeUrl: "/resumes/juliana-ferreira.pdf",
    notes: "5 anos de experiência em laboratório óptico.",
  },
  {
    id: "4",
    name: "Bruno Almeida",
    email: "bruno.almeida@email.com",
    phone: "(16) 97777-6666",
    jobId: "3",
    unitId: "3",
    status: "approved",
    appliedAt: "2024-01-19",
    discProfile: "S",
    temperament: "Fleumático",
    resumeUrl: "/resumes/bruno-almeida.pdf",
    notes: "Muito calmo e paciente. Ideal para pós-venda.",
  },
  {
    id: "5",
    name: "Carla Dias",
    email: "carla.dias@email.com",
    phone: "(11) 96666-5555",
    jobId: "1",
    unitId: "1",
    status: "rejected",
    appliedAt: "2024-01-17",
    discProfile: "I",
    temperament: "Sanguíneo",
    resumeUrl: "/resumes/carla-dias.pdf",
    notes: "Não possui experiência na área.",
  },
];

export const employees = [
  {
    id: "1",
    name: "Carlos Silva",
    email: "carlos.silva@idealize.com",
    role: roles[3],
    unit: units[0],
    hireDate: "2019-03-15",
    discProfile: "D",
    temperament: "Colérico",
    idealizeLevel: "I",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
    performance: 92,
    trainingsCompleted: 18,
    pendingFeedbacks: 2,
  },
  {
    id: "2",
    name: "Ana Souza",
    email: "ana.souza@idealize.com",
    role: roles[3],
    unit: units[1],
    hireDate: "2020-06-01",
    discProfile: "I",
    temperament: "Sanguíneo",
    idealizeLevel: "D",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ana",
    performance: 88,
    trainingsCompleted: 15,
    pendingFeedbacks: 0,
  },
  {
    id: "3",
    name: "Pedro Santos",
    email: "pedro.santos@idealize.com",
    role: roles[0],
    unit: units[0],
    hireDate: "2022-01-10",
    discProfile: "S",
    temperament: "Fleumático",
    idealizeLevel: "E",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Pedro",
    performance: 85,
    trainingsCompleted: 12,
    pendingFeedbacks: 1,
  },
  {
    id: "4",
    name: "Maria Oliveira",
    email: "maria.oliveira@idealize.com",
    role: roles[1],
    unit: units[0],
    hireDate: "2021-08-20",
    discProfile: "C",
    temperament: "Melancólico",
    idealizeLevel: "A",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maria",
    performance: 94,
    trainingsCompleted: 20,
    pendingFeedbacks: 0,
  },
  {
    id: "5",
    name: "João Pereira",
    email: "joao.pereira@idealize.com",
    role: roles[2],
    unit: units[1],
    hireDate: "2023-02-01",
    discProfile: "C",
    temperament: "Melancólico",
    idealizeLevel: "L",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Joao",
    performance: 78,
    trainingsCompleted: 8,
    pendingFeedbacks: 3,
  },
];

export const courses = [
  {
    id: "1",
    title: "Onboarding Consultor de Vendas",
    description: "Trilha completa de integração para novos consultores de vendas.",
    pillar: "Onboarding",
    role: "Consultor de Vendas",
    lessons: 12,
    duration: "8h",
    thumbnail: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400",
    mandatory: true,
    progress: 100,
  },
  {
    id: "2",
    title: "Técnicas de Vendas SPIN",
    description: "Aprenda a metodologia SPIN para aumentar suas conversões.",
    pillar: "Vendas",
    role: "Consultor de Vendas",
    lessons: 8,
    duration: "4h",
    thumbnail: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    mandatory: true,
    progress: 75,
  },
  {
    id: "3",
    title: "Conhecimento de Lentes",
    description: "Tudo sobre tipos de lentes, materiais e tratamentos.",
    pillar: "Técnico",
    role: "Todos",
    lessons: 15,
    duration: "6h",
    thumbnail: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=400",
    mandatory: true,
    progress: 50,
  },
  {
    id: "4",
    title: "Cultura Idealize",
    description: "Conheça os valores, missão e visão da Idealize.",
    pillar: "Cultura",
    role: "Todos",
    lessons: 5,
    duration: "2h",
    thumbnail: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400",
    mandatory: true,
    progress: 100,
  },
  {
    id: "5",
    title: "Rapport e Conexão",
    description: "Como criar conexão genuína com os clientes.",
    pillar: "Vendas",
    role: "Consultor de Vendas",
    lessons: 6,
    duration: "3h",
    thumbnail: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400",
    mandatory: false,
    progress: 25,
  },
  {
    id: "6",
    title: "Laboratório Óptico Básico",
    description: "Fundamentos do trabalho em laboratório óptico.",
    pillar: "Técnico",
    role: "Técnico de Laboratório",
    lessons: 20,
    duration: "12h",
    thumbnail: "https://images.unsplash.com/photo-1581093458791-9f3c3250a8b0?w=400",
    mandatory: true,
    progress: 0,
  },
];

export const notifications = [
  {
    id: "1",
    type: "feedback",
    title: "Feedback pendente",
    message: "Você tem 2 feedbacks pendentes para registrar.",
    read: false,
    createdAt: "2024-01-25T10:30:00",
  },
  {
    id: "2",
    type: "training",
    title: "Treinamento obrigatório",
    message: "Complete o treinamento 'Técnicas de Vendas SPIN' até 30/01.",
    read: false,
    createdAt: "2024-01-24T14:00:00",
  },
  {
    id: "3",
    type: "candidate",
    title: "Novo candidato",
    message: "Mariana Costa se candidatou para Consultor de Vendas.",
    read: true,
    createdAt: "2024-01-23T09:15:00",
  },
];

export const candidateStatuses = [
  { id: "new", label: "Novo", color: "info" },
  { id: "evaluating", label: "Avaliando", color: "warning" },
  { id: "interview", label: "Entrevista", color: "primary" },
  { id: "approved", label: "Aprovado", color: "success" },
  { id: "rejected", label: "Reprovado", color: "destructive" },
] as const;

export const discProfiles = {
  D: { name: "Dominância", color: "destructive", description: "Decisivo, competitivo, direto" },
  I: { name: "Influência", color: "warning", description: "Comunicativo, entusiasta, otimista" },
  S: { name: "Estabilidade", color: "success", description: "Paciente, confiável, colaborativo" },
  C: { name: "Conformidade", color: "info", description: "Analítico, preciso, sistemático" },
};

export const temperaments = {
  Colérico: { color: "destructive", description: "Líder natural, ambicioso, determinado" },
  Sanguíneo: { color: "warning", description: "Extrovertido, alegre, sociável" },
  Fleumático: { color: "success", description: "Calmo, equilibrado, diplomático" },
  Melancólico: { color: "info", description: "Detalhista, perfeccionista, reflexivo" },
};

export const idealizeLevels = {
  I: { name: "Iniciante", description: "Primeiros passos na cultura Idealize" },
  D: { name: "Desenvolvendo", description: "Absorvendo os valores e práticas" },
  E: { name: "Engajado", description: "Praticando ativamente a cultura" },
  A: { name: "Avançado", description: "Referência em cultura e resultados" },
  L: { name: "Líder", description: "Multiplicador da cultura Idealize" },
  I2: { name: "Inspirador", description: "Modelo máximo de excelência" },
  Z: { name: "Zenith", description: "Nível máximo - Cultura incorporada" },
  E2: { name: "Elite", description: "Elite Idealize - Top performers" },
};
